// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz10CSVpmWyiARPSy0UN6EUCg5rGBWBAM',
    appId: '1:839026782154:web:3bcdbaa9660471df86a933',
    messagingSenderId: '839026782154',
    projectId: 'project-888-33c84',
    authDomain: 'project-888-33c84.firebaseapp.com',
    storageBucket: 'project-888-33c84.appspot.com',
    measurementId: 'G-S9JE0EFNKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXo7HM9iLHUbNr3zUgk3TfKIig7rTmSg',
    appId: '1:839026782154:android:553bdec850f5788686a933',
    messagingSenderId: '839026782154',
    projectId: 'project-888-33c84',
    storageBucket: 'project-888-33c84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7u7dGb8V9mi-aNF6if2M2qaytO7zn_SI',
    appId: '1:839026782154:ios:6e04f87d6c250ccb86a933',
    messagingSenderId: '839026782154',
    projectId: 'project-888-33c84',
    storageBucket: 'project-888-33c84.appspot.com',
    androidClientId:
        '839026782154-31r7h83jtacsha2oqfq0g01l7jnk4nbr.apps.googleusercontent.com',
    iosClientId:
        '839026782154-nja6e3tinjh546kppsggg8kllgng90ha.apps.googleusercontent.com',
    iosBundleId: 'com.project888.scheme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7u7dGb8V9mi-aNF6if2M2qaytO7zn_SI',
    appId: '1:839026782154:ios:76de23d42bd30f5986a933',
    messagingSenderId: '839026782154',
    projectId: 'project-888-33c84',
    storageBucket: 'project-888-33c84.appspot.com',
    androidClientId:
        '839026782154-31r7h83jtacsha2oqfq0g01l7jnk4nbr.apps.googleusercontent.com',
    iosClientId:
        '839026782154-f5lekrdqo348848rl7a61lfnhccjfver.apps.googleusercontent.com',
    iosBundleId: 'com.scheme.project888.RunnerTests',
  );
}
